### ISSUE TITLE
tue_robocup breaks on ed.srv.Configure

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/robot_skills#20]
```python 
amigo@athome5 $ rosrun challenge_manipulation manipulation.py amigo
Traceback (most recent call last):
  File "/home/amigo/ros/hydro/system/src/challenge_manipulation/src/manipulation.py", line 41, in <module>
    import pdf
  File "/home/amigo/ros/hydro/repos/https:/github.com/tue-robotics/tue_robocup.git/challenge_manipulation/src/pdf.py", line 11, in <module>
    from robot_skills import world_model_ed
  File "/home/amigo/ros/hydro/system/src/robot_skills/src/robot_skills/world_model_ed.py", line 3, in <module>
    from ed.srv import SimpleQuery, SimpleQueryRequest, UpdateSrv, Configure
ImportError: cannot import name Configure
```

**Comment by LoyVanBeek** [comment]
This was due to using the Configure-service of Ed.
Ed has this on a separate, non-master branch, so robot_skills also cannot depend on this in the master-branch. 
Therefore, checkout the robot_skills feature/use_ed_Configure branch (tue_robotics/robot_skills@  f905fe7586ed367223b5c27a07fc2c7869e42522)
Please note this @svddries and maybe @egeerts
